FROM rucio/test-xrootd@sha256:27d212ec136d6d2ed7029fc445384053acb551805060cae554597a32e6361df4

RUN set -eux; \
    if command -v dnf >/dev/null 2>&1; then PM=dnf; else PM=yum; fi; \
    $PM install -y epel-release; \
    # On EL9, libXrdHttp is in xrootd-server-libs
    # and libXrdHttpTPC is in xrootd-client-libs
    $PM install -y \
        xrootd-scitokens \
        xrootd-server \
        xrootd-server-libs \
        xrootd-client \
        xrootd-client-libs \
        scitokens-cpp \
        ca-certificates; \
    $PM clean all; \
    rm -rf /var/cache/dnf /var/cache/yum; \
    \
    echo "--- Verifying Library Locations ---"; \
    # This will show us exactly where they landed so we can be sure
    find /usr/lib64 -name 'libXrdAccSciTokens*' \
                    -o -name 'libXrdHttp.so*' \
                    -o -name 'libXrdHttpTPC.so*'
