apiVersion: v1
kind: Service
metadata:
  name: {{ include "storm-webdav.fullname" . }}
  labels:
    app: {{ include "storm-webdav.name" . }}
    instance: {{ include "storm-webdav.fullname" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.https }}
      targetPort: https
      name: https
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      name: http
  selector:
    app: {{ include "storm-webdav.name" . }}
    instance: {{ include "storm-webdav.fullname" . }}
