[pytest]
addopts = -p no:cacheprovider -v -s --tb=short
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s %(levelname)-7s %(name)s: %(message)s
log_cli_date_format = %H:%M:%S

filterwarnings =
    ignore::DeprecationWarning:M2Crypto.*
    ignore:Unverified HTTPS request is being made.*:urllib3.exceptions.InsecureRequestWarning
