apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xrootd-scitokens.fullname" . }}
  labels:
    app: {{ include "xrootd-scitokens.name" . }}
    instance: {{ include "xrootd-scitokens.fullname" . }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "xrootd-scitokens.name" . }}
      instance: {{ include "xrootd-scitokens.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "xrootd-scitokens.name" . }}
        instance: {{ include "xrootd-scitokens.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      hostname: {{ include "xrootd-scitokens.fullname" . }}
      containers:
        - name: xrootd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: XRDPORT
              value: {{ .Values.xrdPort | quote }}
          command: ["/bin/bash", "/usr/local/bin/docker-entrypoint.sh"]
          ports:
            - name: xrootd
              containerPort: {{ .Values.xrdPort }}
              protocol: TCP
          volumeMounts:
            - name: certs
              mountPath: /tmp/xrdcert.pem
              subPath: xrdcert.pem
              readOnly: true
            - name: certs
              mountPath: /tmp/xrdkey.pem
              subPath: xrdkey.pem
              readOnly: true
            - name: certs
              mountPath: /etc/grid-security/certificates/5fca1cb1.0
              subPath: rucio_ca.pem
              readOnly: true
            - name: configs
              mountPath: /etc/xrootd/xrdrucio.cfg.tmpl
              subPath: xrdrucio.cfg
              readOnly: true
            - name: configs
              mountPath: /etc/xrootd/authdb
              subPath: authdb
              readOnly: true
            - name: configs
              mountPath: /etc/xrootd/scitokens.conf
              subPath: scitokens.conf
              readOnly: true
            - name: scripts
              mountPath: /usr/local/bin/docker-entrypoint.sh
              subPath: docker-entrypoint-oidc.sh
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: certs
          secret:
            secretName: {{ .Values.certsSecret }}
        - name: configs
          configMap:
            name: {{ .Values.configsConfigMap }}
        - name: scripts
          configMap:
            name: {{ .Values.scriptsConfigMap }}-xrootd
            defaultMode: 0755
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
