apiVersion: v1
kind: Service
metadata:
  name: {{ include "xrootd-scitokens.fullname" . }}
  labels:
    app: {{ include "xrootd-scitokens.name" . }}
    instance: {{ include "xrootd-scitokens.fullname" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: xrootd
      protocol: TCP
      name: xrootd
  selector:
    app: {{ include "xrootd-scitokens.name" . }}
    instance: {{ include "xrootd-scitokens.fullname" . }}
