[Global]
onmissing = passthrough
# HACK: If your token has azp: rucio-oidc, add it here to satisfy the validator
audience = https://xrd3:1094, https://xrd4:1094, fts-oidc, rucio-oidc

[Issuer Keycloak]
issuer = https://keycloak:8443/realms/rucio
base_path = /data
map_subject = True
# default_user is a fallback, but 'u *' in authdb is more robust
default_user = xrootd
