name=data
rootPath=/storage/data
accessPoints=/data
orgs=http://keycloak:8080/realms/rucio
anonymousReadEnabled=true
authenticatedReadEnabled=true
voMapEnabled=false
orgsGrantReadPermission=false
orgsGrantWritePermission=false
wlcgScopeAuthzEnabled=false
fineGrainedAuthzEnabled=true