FROM rucio/rucio-clients@sha256:d03fd88c2b6fe50a64a95cc7001486208aa115e3997658359158746eb178cc1d

USER root

RUN dnf install -y --setopt=install_weak_deps=False dnf-plugins-core \
 && dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo \
 && dnf install -y --setopt=install_weak_deps=False docker-ce-cli \
 && dnf clean all \
 && rm -rf /var/cache/dnf

ARG TARGETARCH

RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/${TARGETARCH}/kubectl" \
    && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl \
    && rm kubectl

RUN docker --version
RUN kubectl version --client
