FROM --platform=linux/amd64 ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive
ARG STORM_VERSION=1.13.0
ARG TEAPOT_REPO=https://github.com/interTwin-eu/teapot.git
ARG TEAPOT_REF=main

RUN apt-get update && apt-get install -y --no-install-recommends \
    adduser curl ca-certificates openssl python3 \
    openjdk-21-jre-headless sudo \
    git debhelper dh-python python3-pip wget rpm2cpio cpio build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN git clone --depth 1 --branch "${TEAPOT_REF}" "${TEAPOT_REPO}" /usr/src/teapot \
    && cd /usr/src/teapot \
    && STORM_VERSION=${STORM_VERSION} dpkg-buildpackage -us -uc -b \
    && apt-get update \
    && apt-get install -y --no-install-recommends /usr/src/teapot_*.deb \
    && rm -rf /usr/src/teapot* /usr/src/*.deb /usr/src/*.buildinfo /usr/src/*.changes \
    && rm -rf /var/lib/apt/lists/*

RUN echo "root ALL=(teapot) NOPASSWD: ALL" >> /etc/sudoers

EXPOSE 8081
COPY shared/scripts/teapot/docker-entrypoint.sh /usr/local/bin/teapot-entrypoint.sh
RUN chmod +x /usr/local/bin/teapot-entrypoint.sh
ENTRYPOINT ["/usr/local/bin/teapot-entrypoint.sh"]
