{{- if .Values.rucio.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rucio-server-cfg
  labels:
    app.kubernetes.io/name: rucio-storage-testbed
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  server.cfg: {{ .Files.Get "files/configs/rucio/server.cfg" | b64enc }}
  alembic.ini: {{ .Files.Get "files/configs/rucio/alembic.ini" | b64enc }}
{{- end }}
{{- if (index .Values "rucio-oidc").enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rucio-oidc-server-cfg
  labels:
    app.kubernetes.io/name: rucio-storage-testbed
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  oidc-server.cfg: {{ .Files.Get "files/configs/rucio/oidc-server.cfg" | b64enc }}
  alembic-oidc.ini: {{ .Files.Get "files/configs/rucio/alembic-oidc.ini" | b64enc }}
  idpsecrets.json: {{ .Files.Get "files/configs/rucio/idpsecrets.json" | b64enc }}
{{- end }}
