apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fts.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "fts.fullname" . }}-exec
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "create"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "fts.fullname" . }}-exec
subjects:
  - kind: ServiceAccount
    name: {{ include "fts.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "fts.fullname" . }}-exec
  apiGroup: rbac.authorization.k8s.io
