name=data
rootPath=/storage/data
accessPoints=/data
orgs=https://keycloak:8443/realms/rucio
fineGrainedAuthzEnabled=true
wlcgScopeAuthzEnabled=true
anonymousReadEnabled=true
authenticatedReadEnabled=true
