storm:
  authz:
    policies:
      - sa: data
        actions:
          - all
        effect: permit
        description: "Grant full access to rucio users"
        principals:
          - type: JWT_GROUP
            params:
              iss: "https://keycloak:8443/realms/rucio"
              group: "/rucio/users"
      - sa: data
        actions:
          - all
        effect: permit
        description: "Grant full access to atlas users"
        principals:
          - type: JWT_GROUP
            params:
              iss: "https://keycloak:8443/realms/rucio"
              group: "/atlas/users"
