name=data
rootPath=/storage/data
accessPoints=/data
orgs=https://keycloak:8443/realms/rucio
anonymousReadEnabled=true
authenticatedReadEnabled=true
voMapEnabled=false
orgsGrantReadPermission=false
orgsGrantWritePermission=false
wlcgScopeAuthzEnabled=false
fineGrainedAuthzEnabled=true
