server {
    listen 9000 ssl;
    ssl_certificate     /etc/nginx/certs/public.crt;
    ssl_certificate_key /etc/nginx/certs/private.key;
    location / {
        proxy_pass http://minio2:9000;
        proxy_set_header Host minio2:9000;
    }
}
